export const certificationsData = [
  {
    name: "AI for India",
    id: "ai-for-india-" + Math.random().toString(36).substr(2, 9),
    description: "This certification covers fundamental concepts of Artificial Intelligence and its applications in the Indian context.",
    date: "October 2023",
    imageUrl: "/images/AI for india .jpg",
  },
  {
    name: "Embedded Systems Emertex",
    id: "embedded-systems-emertex-" + Math.random().toString(36).substr(2, 9),
    description: "This certification focuses on the design and development of embedded systems, with a special emphasis on real-time applications.",
    date: "July 2022",
    imageUrl: "/images/Emmbeded Systems Emertex.jpg",
  },
  {
    name: "Embedded System NIELIT",
    id: "embedded-system-nielit-" + Math.random().toString(36).substr(2, 9),
    description: "This certification, provided by NIELIT, covers core concepts and practical applications of embedded systems.",
    date: "December 2022",
    imageUrl: "/images/Emmbeded system  NIELIT .jpg",
  },
  {
    name: "Embedded Systems with Arm",
    id: "embedded-systems-arm-" + Math.random().toString(36).substr(2, 9),
    description: "This certification focuses on embedded systems development using Arm architecture, covering hardware and software aspects.",
    date: "May 2023",
    imageUrl: "/images/Emmbeded systems with Arm.jpg",
  },
  {
    name: "IOT Application with Arm",
    id: "iot-application-arm-" + Math.random().toString(36).substr(2, 9),
    description: "This certification covers the development of Internet of Things applications utilizing Arm-based microcontrollers and architectures.",
    date: "March 2023",
    imageUrl: "/images/IOT Application with Arm.jpg",
  },
  {
    name: "Internet of Things Codtech",
    id: "iot-codtech-" + Math.random().toString(36).substr(2, 9),
    description: "This certification, by Codtech, introduces the core concepts of IoT and its practical applications.",
    date: "August 2021",
    imageUrl: "/images/Internet of things  codtech.jpg",
  },
  {
    name: "Internet of Things APSSDC",
    id: "iot-apssdc-" + Math.random().toString(36).substr(2, 9),
    description: "This certification by APSSDC focuses on the development and deployment of IoT solutions and applications.",
    date: "September 2022",
    imageUrl: "/images/Internet of things APSSDC.jpg",
  },
  {
    name: "Introduction to Cloud Computing",
    id: "cloud-computing-" + Math.random().toString(36).substr(2, 9),
    description: "This certification provides a comprehensive overview of cloud computing, including key concepts and services.",
    date: "January 2024",
    imageUrl: "/images/Introduction to Cloud Computing.jpg",
  },
  {
    name: "Machine Learning",
    id: "machine-learning-" + Math.random().toString(36).substr(2, 9),
    description: "This certification covers fundamental machine learning algorithms, techniques, and applications.",
    date: "November 2023",
    imageUrl: "/images/Machine Learning .jpg",
  },
  {
    name: "MEMS Fabrication",
    id: "mems-fabrication-" + Math.random().toString(36).substr(2, 9),
    description: "This certification focuses on the principles and practices of Micro-Electro-Mechanical Systems (MEMS) fabrication.",
    date: "June 2022",
    imageUrl: "/images/Mems Fabrication.jpg",
  },
  {
    name: "Python",
    id: "python-" + Math.random().toString(36).substr(2, 9),
    description: "This certification validates proficiency in Python programming, covering its fundamentals and advanced concepts.",
    date: "April 2021",
    imageUrl: "/images/Python .jpg",
  },
  {
    name: "SCL",
    id: "scl-" + Math.random().toString(36).substr(2, 9),
    description: "This certification covers the design and layout aspects of semiconductor circuits.",
    date: "February 2023",
    imageUrl: "/images/SCL .jpg",
  },
  {
    name: "Semiconductor Fabrication",
    id: "semiconductor-fabrication-" + Math.random().toString(36).substr(2, 9),
    description: "This certification introduces the processes involved in semiconductor manufacturing and fabrication.",
    date: "August 2022",
    imageUrl: "/images/Semiconductor Fabrication.jpg",
  },
  {
    name: "Sidvi Foundation",
    id: "sidvi-foundation-" + Math.random().toString(36).substr(2, 9),
    description: "This certification covers various aspects of technology, innovation, and entrepreneurship.",
    date: "March 2021",
    imageUrl: "/images/Sidvi foundation.jpg",
  },
  {
    name: "VLSI for Beginners",
    id: "vlsi-for-beginners-" + Math.random().toString(36).substr(2, 9),
    description: "This certification introduces the basics of Very Large Scale Integration (VLSI) technology.",
    date: "September 2021",
    imageUrl: "/images/VLSI for Beginners.jpg",
  },
  {
    name: "VLSI SOC Design Using Verilog",
    id: "vlsi-soc-design-verilog-" + Math.random().toString(36).substr(2, 9),
    description: "This certification focuses on the design of System-on-Chip (SoC) using Verilog HDL.",
    date: "December 2023",
    imageUrl: "/images/VLSI soc Design Using Verilog.jpg",
  },
  {
    name: "VLSI Digital Design",
    id: "vlsi-digital-design-" + Math.random().toString(36).substr(2, 9),
    description: "This certification covers core principles and techniques in VLSI digital circuit design.",
    date: "January 2023",
    imageUrl: "/images/Vlsi Digital Design.jpg",
  },
  {
    name: "Digital Image Processing",
    id: "digital-image-processing-" + Math.random().toString(36).substr(2, 9),
    description: "This certification provides a comprehensive understanding of digital image processing algorithms and techniques.",
    date: "July 2023",
    imageUrl: "/images/digital image processing.jpg",
  },
  {
    name: "Machine Learning for Semiconductors",
    id: "machine-learning-semiconductors-" + Math.random().toString(36).substr(2, 9),
    description: "This certification explores the applications of machine learning within the semiconductor industry.",
    date: "June 2023",
    imageUrl: "/images/meachine Learning for semiconductors.jpg",
  },
];